const Joi = require('joi');
module.exports.listingSchema=Joi.object({
    listings:Joi.object({
        companyName:Joi.string().required(),
        desc:Joi.string().required(),
        img:Joi.string().required(),
        role:Joi.string().required(),
        location:Joi.string().required(),
        duration:Joi.string().required(),
        stipend:Joi.number().required(),
        deadline:Joi.string().required(),
        requirements:Joi.string().required(),
        contactEmail:Joi.string().required(),
    }).required(),
});
module.exports.experienceSchema=Joi.object({
    Experience:Joi.object({
        comment:Joi.string().required(),
    }).required(),
});
module.exports.applicantSchema=Joi.object({
    applicant:Joi.object({
        applicantName:Joi.string().required(),
        applicantEmail:Joi.string().required(),
        resume:Joi.string().required(),
        dateApplied:Joi.date().required()
    }).required(),
})